[theme]
base = "light"
primaryColor = "#2D6AB4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EEF3FA"
textColor = "#242A30"
font = "sans serif"

[server]
maxUploadSize = 60

[browser]
gatherUsageStats = false
